name: Pytest

on:
  push:
    paths:
      - "backend/**"
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv sync --extra dev

      - name: Run pytest
        env:
          GS_DATABASE_USER: ci_user
          GS_DATABASE_PASSWORD: ci_password
          GS_DATABASE_LOCATION: localhost
          GS_DATABASE_PORT: 5432
          GS_DATABASE_NAME: gs
          KEYCLOAK_URL: http://localhost:8080
          KEYCLOAK_REALM: mcc
          KEYCLOAK_CLIENT_ID: ground-station
          KEYCLOAK_CLIENT_SECRET: foobar676767brainrot
          KEYCLOAK_CALLBACK_URL: http://localhost:8000/callback
          EMAIL_MAIL_USERNAME: ""
          EMAIL_MAIL_PASSWORD: ""
          EMAIL_MAIL_SERVER: ""
          EMAIL_MAIL_PORT: 465
          EMAIL_MAIL_FROM: "john.doe@example.com"
          EMAIL_MAIL_FROM_NAME: "John Doe"
        run: |
          uv run pytest -m "not integration"
